config/routes.rb
Rails.application.routes.draw do
	root to: "posts#index"
  resources :authors do
  	resources :posts
  end
	resources :posts, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :author
	has_attached_file :image, styles: { small: "100x100", med: "200x200", large: "400x400" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	validates :title, 			 :presence => true,
													 :length => { :minimum => 5, :maximum => 40}
	validates :introduction, :presence => true,
													 :length => { :minimum => 5}
	validates :body, 				 :presence => true,
										       :length => { :minimum => 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	before_action :set_author, only: [:show, :edit, :update, :destroy]

	def index
		@authors = Author.all
	end

	def new
		@author = Author.new
	end

	def show
	end

	def edit
	end

	def create
		@author = Author.new(author_params)

		respond_to do |format|
			if @author.save 
				format.html { redirect_to @author, notice: 'Author was successfully created'}
				format.json { render :show, status: :created, location: @author}
			else
				format.html { render :new }
				format.json { render json: @author.errors, status: :unprocessable_entity}
			end

		end
	end

	def update
		respond_to do |format|
			if @author.update(author_params) 
				format.html { redirect_to @author, notice: 'Author was successfully upated'}
				format.json { render :show, status: :ok, location: @author}
			else
				format.html { render :edit }
				format.json { render json: @author.errors, status: :unprocessable_entity}
			end

		end
	end

	def destroy
		@author.destroy
		respond_to do |format|
			format.html { redirect_to authors_url, notice: 'Author was successfully destroyed'}
			format.json { head :no_content}
		end
	end

	private

	def set_author
		@author = Author.find(params[:id])
	end

	def author_params
		params.require(:author).permit(:name, :biography)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_author

  # GET /posts
  # GET /posts.json
  def index
    if params[:author_id]
      @posts = Post.where(author_id: params[:author_id])
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @author.posts.create(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to author_post_path(@author, @post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to author_posts_path(@author), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_author
      if params[:author_id]
        @author = Author.find(params[:author_id])
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :introduction, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :author_name %>
  </div>

  <div class="field">
    <%= form.label :biography %>
    <%= form.text_area :biography, id: :author_biography %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Biography</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.biography %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Posts', author_posts_path(author) %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @author.biography %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloggingHard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for([@author, @post], html: { multipart: true }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :introduction %>
    <%= form.text_area :introduction, id: :post_introduction %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :post_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Introduction</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.introduction %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>

        <% if @author %>
          <td><%= link_to 'Edit', edit_author_post_path(@author, post) %></td>
          <td><%= link_to 'Destroy', [@author, post], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if @author %>
  <%= link_to 'New Post', new_author_post_path(@author.id) %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= @author.name %>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Introduction:</strong>
  <%= @post.introduction %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Image</strong>
  <%= image_tag @post.image.url(:small) %>
</p>
<% if @author %>

<%= link_to 'Edit', edit_author_post_path(@author, @post) %> |

<% end %>

<%= link_to 'Back', posts_path %>